---
layout: post
title: 'Promise'
date: 2020-11-21
author: 廉兆
categories: 技术
cover: '/assets/img/cover/marguerite-729510_640.jpg'
tags: JavaScript ES6 Promise
---

> Promise 是在 ES6 中新增的一种用于解决异步编程方案

### 一句话介绍

Promise 是在 ES6 中新增的一种用于解决异步编程方案

### 产生的原因

#### 回调地狱

在 Promise 出现之前，处理异步的问题可能会使用多层的回调函数，导致代码的嵌套太深，引发回调地狱。

### 生命周期

每一个 Promise 对象都有 3 种状态

1. pending（进行中）
2. resolved（已解决）
3. rejected（已拒绝）

Promise 在创建时处于 pending 状态，状态的改变只有两种可能，一种是在 Promise 执行成功时，由 pending 状态改变为 resolved，另一种是在 Promise 执行失败时，由 pending 状态改变为 rejected。

状态一旦改变，就不能再改变，状态改变一次后得到的就是 Promise 的终态。

### 基本用法

Promise 对象本身是一个构造函数，可以通过 new 操作符生成 Promise 实例

```js
const promise = new Promise((resolve, reject) => {
  // 异步请求的结果
  let flag = true
  if (flag) {
    resolve()
  } else {
    reject()
  }
})
```

#### then 函数

Promise 在原型属性上添加了一个 `then()` 函数，表示在 Promise 实例状态改变时执行的回调函数。

`then()` 函数接受两个参数，一个是执行 `resolve()` 之后的回调函数，第二个是执行 `reject()` 之后的回调函数，第二个参数通常被省略。

`then()` 函数返回一个新的 Promise 实例，因此可以使用链式调用 `then()` 函数，在上一个 `then()` 函数内部 return 的值会被作为下一个 `then()` 函数的参数值。

```js
const promise = new Promise((resolve, reject) => {
  resolve(1)
})
  .then(result => {
    console.log(result) // 1
    return 2
  })
  .then(result => {
    console.log(result) // 2
    return 3
  })
  .then(result => {
    console.log(result) // 3
    return 4
  })
  .then(result => {
    console.log(result) // 4
  })
```

#### catch 函数

`catch()` 函数是 Promise 执行失败之后的回调，它所接受的参数就是执行 `reject()` 函数时传递的参数。

除了手动执行 `reject()` 函数之外，只要在 Promise 执行的过程中出现了异常，就会被自动抛出，并触发 `reject(err)` ，然后我们就可以在 `catch()` 函数中对异常进行处理。

被成功 catch 的 Promise 的状态会变更为 resolved，异常没有被捕获的 Promise，状态才会变更为 rejected。

```js
const promise = new Promise((resolve, reject) => {
  console.log(null.name)
})
  .then(result => {
    console.log('success:', result)
  })
  .catch(result => {
    console.log('failed:', result) // failed: TypeError: Cannot read property 'name' of null
  })
```

#### Promise.all()

`all()` 函数是 Promise 本身的静态函数，用于将多个 Promise 对象包装成一个新的 Promise 实例。

```js
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1)
  }, 3000)
})
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(2)
  }, 2000)
})
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(3)
  }, 1000)
})
const p = Promise.all([p1, p2, p3])
p.then(result => {
  console.log(result) // [1, 2, 3]
}).catch(result => {
  console.log(result)
})
```

只有当数组中所有的实例都变为 resolved 时，才会触发 p 的 `then()` 函数，返回值为一个数组，与传入的 Promise 对象顺序一一对应；

当数组中任意实例变为 rejected 状态时，会触发 p 的 `catch()` 函数，返回的值是此 `reject()` 函数捕获到的内容。

#### Promise.race()

同样是 Promise 类本身的静态函数，用于将多个 Promise 对象包装成一个新的 Promise 实例。

如果多个 Promise 实例中有任意一个的状态发生了变化，这个新示例的状态就会跟随发生变化，最先改变的那个 Promise 实例的返回值将作为新实例的回调函数的参数。
